/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MethodRouteImport } from './routes/method'
import { Route as PermanentMakeupRouteImport } from './routes/permanent-makeup'
import { Route as PmuPoliciesRouteImport } from './routes/pmu-policies'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AcademyIndexRouteImport } from './routes/academy.index'
import { Route as AcademySlugRouteImport } from './routes/academy.$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as AccountOrdersIdRouteImport } from './routes/account_.orders.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const PermanentMakeupRoute = PermanentMakeupRouteImport.update({
  id: '/permanent-makeup',
  path: '/permanent-makeup',
  getParentRoute: () => rootRouteImport,
} as any)
const PmuPoliciesRoute = PmuPoliciesRouteImport.update({
  id: '/pmu-policies',
  path: '/pmu-policies',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyIndexRoute = AcademyIndexRouteImport.update({
  id: '/academy/',
  path: '/academy/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademySlugRoute = AcademySlugRouteImport.update({
  id: '/academy/$slug',
  path: '/academy/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersIdRoute = AccountOrdersIdRouteImport.update({
  id: '/account_/orders/$id',
  path: '/account/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/method': typeof MethodRoute
  '/permanent-makeup': typeof PermanentMakeupRoute
  '/pmu-policies': typeof PmuPoliciesRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/wishlist': typeof WishlistRoute
  '/academy/$slug': typeof AcademySlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/academy/': typeof AcademyIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/method': typeof MethodRoute
  '/permanent-makeup': typeof PermanentMakeupRoute
  '/pmu-policies': typeof PmuPoliciesRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/wishlist': typeof WishlistRoute
  '/academy/$slug': typeof AcademySlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/academy': typeof AcademyIndexRoute
  '/shop': typeof ShopIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/method': typeof MethodRoute
  '/permanent-makeup': typeof PermanentMakeupRoute
  '/pmu-policies': typeof PmuPoliciesRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/wishlist': typeof WishlistRoute
  '/academy/$slug': typeof AcademySlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/academy/': typeof AcademyIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/account_/orders/$id': typeof AccountOrdersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/forgot-password'
    | '/login'
    | '/method'
    | '/permanent-makeup'
    | '/pmu-policies'
    | '/register'
    | '/reset-password'
    | '/returns'
    | '/wishlist'
    | '/academy/$slug'
    | '/checkout/success'
    | '/learn/$slug'
    | '/shop/$slug'
    | '/academy/'
    | '/shop/'
    | '/account/orders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/forgot-password'
    | '/login'
    | '/method'
    | '/permanent-makeup'
    | '/pmu-policies'
    | '/register'
    | '/reset-password'
    | '/returns'
    | '/wishlist'
    | '/academy/$slug'
    | '/checkout/success'
    | '/learn/$slug'
    | '/shop/$slug'
    | '/academy'
    | '/shop'
    | '/account/orders/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cart'
    | '/forgot-password'
    | '/login'
    | '/method'
    | '/permanent-makeup'
    | '/pmu-policies'
    | '/register'
    | '/reset-password'
    | '/returns'
    | '/wishlist'
    | '/academy/$slug'
    | '/checkout/success'
    | '/learn/$slug'
    | '/shop/$slug'
    | '/academy/'
    | '/shop/'
    | '/account_/orders/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MethodRoute: typeof MethodRoute
  PermanentMakeupRoute: typeof PermanentMakeupRoute
  PmuPoliciesRoute: typeof PmuPoliciesRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReturnsRoute: typeof ReturnsRoute
  WishlistRoute: typeof WishlistRoute
  AcademySlugRoute: typeof AcademySlugRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  LearnSlugRoute: typeof LearnSlugRoute
  ShopSlugRoute: typeof ShopSlugRoute
  AcademyIndexRoute: typeof AcademyIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
  AccountOrdersIdRoute: typeof AccountOrdersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permanent-makeup': {
      id: '/permanent-makeup'
      path: '/permanent-makeup'
      fullPath: '/permanent-makeup'
      preLoaderRoute: typeof PermanentMakeupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pmu-policies': {
      id: '/pmu-policies'
      path: '/pmu-policies'
      fullPath: '/pmu-policies'
      preLoaderRoute: typeof PmuPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/': {
      id: '/academy/'
      path: '/academy'
      fullPath: '/academy/'
      preLoaderRoute: typeof AcademyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/$slug': {
      id: '/academy/$slug'
      path: '/academy/$slug'
      fullPath: '/academy/$slug'
      preLoaderRoute: typeof AcademySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/orders/$id': {
      id: '/account_/orders/$id'
      path: '/account/orders/$id'
      fullPath: '/account/orders/$id'
      preLoaderRoute: typeof AccountOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CartRoute: CartRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MethodRoute: MethodRoute,
  PermanentMakeupRoute: PermanentMakeupRoute,
  PmuPoliciesRoute: PmuPoliciesRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReturnsRoute: ReturnsRoute,
  WishlistRoute: WishlistRoute,
  AcademySlugRoute: AcademySlugRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  LearnSlugRoute: LearnSlugRoute,
  ShopSlugRoute: ShopSlugRoute,
  AcademyIndexRoute: AcademyIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
  AccountOrdersIdRoute: AccountOrdersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
